// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220207025459_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Domain.Entities.Admin.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("идентификатор");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_firstname")
                        .HasComment("имя");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_lastname")
                        .HasComment("фамилия");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("c_middlename")
                        .HasComment("отчество");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_type")
                        .HasComment("тип");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_username")
                        .HasComment("логин");

                    b.HasKey("Id")
                        .HasName("pk_cd_users");

                    b.HasIndex("Id", "TypeId")
                        .HasDatabaseName("ix_cd_users_id_f_type");

                    b.ToTable("cd_users", "admin");

                    b
                        .HasComment("пользователи");
                });

            modelBuilder.Entity("Domain.Entities.Common.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("идентификатор");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("f_type")
                        .HasComment("тип");

                    b.HasKey("Id", "TypeId")
                        .HasName("pk_cd_entities");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_cd_entities_f_type");

                    b.ToTable("cd_entities", "common");

                    b
                        .HasComment("сущности");
                });

            modelBuilder.Entity("Domain.Entities.Common.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasComment("идентификатор");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_name")
                        .HasComment("название");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_schema")
                        .HasComment("схема");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_slug")
                        .HasComment("код");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_tablename")
                        .HasComment("таблица");

                    b.HasKey("Id")
                        .HasName("pk_cs_entity_types");

                    b.ToTable("cs_entity_types", "common");

                    b
                        .HasComment("типы сущностей");
                });

            modelBuilder.Entity("Domain.Entities.Admin.User", b =>
                {
                    b.HasOne("Domain.Entities.Common.Entity", null)
                        .WithMany()
                        .HasForeignKey("Id", "TypeId")
                        .HasConstraintName("fk_cd_users_cd_entities_entityid_entitytypeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Common.Entity", b =>
                {
                    b.HasOne("Domain.Entities.Common.EntityType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .HasConstraintName("fk_cd_entities_cs_entity_types_f_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
