// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.DbContexts;

namespace server.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211125174036_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("server.Entities.Admin.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Create")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("b_create")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("b_delete")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("Read")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("b_read")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TypeId")
                        .HasColumnName("f_type")
                        .HasColumnType("uuid");

                    b.Property<bool>("Update")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("b_update")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id")
                        .HasName("pk_cd_claims");

                    b.ToTable("cd_claims","admin");
                });

            modelBuilder.Entity("server.Entities.Admin.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("c_name")
                        .HasColumnType("text");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnName("c_schema")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnName("c_slug")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnName("c_tablename")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_cs_entity_types");

                    b.ToTable("cs_entity_types","admin");
                });

            modelBuilder.Entity("server.Entities.Admin.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("c_password")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("c_username")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_cd_users");

                    b.ToTable("cd_users","admin");
                });

            modelBuilder.Entity("server.Entities.Admin.UserClaim", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnName("f_user")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnName("f_claim")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ClaimId")
                        .HasName("pk_cd_user_claims");

                    b.HasIndex("ClaimId");

                    b.ToTable("cd_user_claims","admin");
                });

            modelBuilder.Entity("server.Entities.Common.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeId")
                        .HasColumnName("f_type")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_cd_entities");

                    b.HasIndex("TypeId");

                    b.ToTable("cd_entities","common");
                });

            modelBuilder.Entity("server.Entities.Common.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("c_first_name")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("c_last_name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_cd_persons");

                    b.ToTable("cd_persons","common");
                });

            modelBuilder.Entity("server.Entities.Admin.Claim", b =>
                {
                    b.HasOne("server.Entities.Admin.EntityType", "Type")
                        .WithMany()
                        .HasForeignKey("Id")
                        .HasConstraintName("fk_cd_claims_cs_entity_types_f_type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Entities.Common.Entity", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .HasConstraintName("fk_cd_claims_cd_entities_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Entities.Admin.User", b =>
                {
                    b.HasOne("server.Entities.Common.Entity", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .HasConstraintName("fk_cd_users_cd_entities_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Entities.Admin.UserClaim", b =>
                {
                    b.HasOne("server.Entities.Admin.Claim", "Claim")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .HasConstraintName("fk_cd_user_claims_cd_claims_f_claim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Entities.Admin.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_cd_user_claims_cd_claims_f_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Entities.Common.Entity", b =>
                {
                    b.HasOne("server.Entities.Admin.EntityType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .HasConstraintName("fk_cd_entities_cs_entitie_types_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("server.Entities.Common.Person", b =>
                {
                    b.HasOne("server.Entities.Common.Entity", null)
                        .WithMany()
                        .HasForeignKey("Id")
                        .HasConstraintName("fk_cd_persons_cd_entities_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
